version: "3.7"

services:
  secondary:
    image: atsigncompany/secondary:dess
    command: "-a ${ATSIGN} -p ${PORT} -s ${SECRET}"
    ports:
      - target: ${PORT}
        published: ${PORT}
    volumes:
      - ~/atsign/etc/live/${DOMAIN}:/atsign/certs
      - ~/atsign/etc/archive/${DOMAIN}:/archive/${DOMAIN}
      - ~/atsign/${ATSIGN}/storage:/atsign/storage
    networks:
      second: {}

  shepherd:
    image: mazzolino/shepherd:latest
    environment:
      TZ: 'US/PST'
      SLEEP_TIME: '30m'
      VERBOSE: 'true'
      FILTER_SERVICES: 'label=com.docker.stack.image=atsigncompany/secondary:dess'
      IMAGE_AUTOCLEAN_LIMIT: 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  second:
    external: true
    name: secondaries
